name = "synthire-backend"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"
JWT_EXPIRY_SECONDS = "86400"
FRONTEND_ORIGIN = "http://localhost:3000"
MAX_UPLOAD_BYTES = "10485760"
EMAIL_PROVIDER = "sendgrid" #"resend"
RESEND_FROM_EMAIL = "onboarding@resend.dev"
RESEND_FROM_NAME = "Synthire"
SENDGRID_FROM_EMAIL = "adigaikwad4321@gmail.com"
EMAIL_QUEUE_INTERVAL_SECONDS = "30"
EMAIL_MAX_RETRIES = "3"

# After running: wrangler d1 create synthire-prod
# Replace REPLACE_WITH_YOUR_DATABASE_ID with the output database_id
[[d1_databases]]
binding = "DB"
database_name = "synthire-prod"
database_id = "f6a8faf6-0220-4870-a66b-cbca43405762"
migrations_dir = "src/db/migrations"

# After running: wrangler r2 bucket create synthire-resumes
[[r2_buckets]]
binding = "RESUME_BUCKET"
bucket_name = "synthire-resumes"

# After running: wrangler kv:namespace create KV_CACHE
# Replace REPLACE_WITH_YOUR_KV_ID with the output id
[[kv_namespaces]]
binding = "KV_CACHE"
id = "6da4fc72343e4286a9080b741ad98bc7"
preview_id = "a808db59def7494d8ad4718dea31cf3b"

# After running: wrangler vectorize create synthire-embeddings --dimensions=1024 --metric=cosine
[[vectorize]]
binding = "VECTORIZE"
index_name = "synthire-embeddings"

# Workers AI (built-in, no setup needed)
[ai]
binding = "AI"

# Scheduled worker for email queue processor (runs every minute)
[triggers]
crons = ["* * * * *"]

[env.production.vars]
ENVIRONMENT = "production"
FRONTEND_ORIGIN = "https://synthire-frontend.pages.dev"
EMAIL_PROVIDER = "sendgrid"
RESEND_FROM_EMAIL = "onboarding@resend.dev"
RESEND_FROM_NAME = "Synthire"
SENDGRID_FROM_EMAIL = "adigaikwad4321@gmail.com"
JWT_EXPIRY_SECONDS = "86400"
MAX_UPLOAD_BYTES = "10485760"
EMAIL_QUEUE_INTERVAL_SECONDS = "30"
EMAIL_MAX_RETRIES = "3"

[[env.production.d1_databases]]
binding = "DB"
database_name = "synthire-prod"
database_id = "f6a8faf6-0220-4870-a66b-cbca43405762"
migrations_dir = "src/db/migrations"

[[env.production.r2_buckets]]
binding = "RESUME_BUCKET"
bucket_name = "synthire-resumes"

[[env.production.kv_namespaces]]
binding = "KV_CACHE"
id = "6da4fc72343e4286a9080b741ad98bc7"

[[env.production.vectorize]]
binding = "VECTORIZE"
index_name = "synthire-embeddings"

[env.production.ai]
binding = "AI"

[env.production.triggers]
crons = ["* * * * *"]
