import { createMiddleware } from 'hono/factory'
import type { Env } from '../types/bindings'

export const corsMiddleware = createMiddleware<{ Bindings: Env }>(async (c, next) => {
  const requestOrigin = c.req.header('Origin') || ''
  const configured = c.env.FRONTEND_ORIGIN || 'http://localhost:3000'

  // In dev, allow any localhost origin regardless of port.
  const isLocalhost = /^https?:\/\/localhost(:\d+)?$/.test(requestOrigin)
  const allowed = isLocalhost ? requestOrigin : configured

  // Set CORS headers before next() so they appear on ALL responses,
  // including error responses generated by onError (which don't re-run middleware).
  c.header('Access-Control-Allow-Origin', allowed)
  c.header('Vary', 'Origin')

  if (c.req.method === 'OPTIONS') {
    c.header('Access-Control-Allow-Methods', 'GET,POST,PATCH,DELETE,OPTIONS')
    c.header('Access-Control-Allow-Headers', 'Content-Type,Authorization')
    c.header('Access-Control-Max-Age', '86400')
    return c.body(null, 204)
  }

  await next()
})
